version: '3'

services:
  api:
    container_name: clients-api
    image: clients-api
    build: ./api
    env_file:
      - ./env/api.env
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    container_name: clients-database
    image: clients-database
    build: ./database
    restart: always
    env_file:
      - ./env/database.env
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: