apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      volumes:
        - name: tasks-volume
          hostPath:
            path: /tasks
            type: DirectoryOrCreate
      containers:
      - name: tasks-api
        volumeMounts:
          - name: tasks-volume
            mountPath: /app/tasks
        env:
          - name: AUTH_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: project-env
                key: AUTH_ADDRESS
          - name: TASKS_FOLDER
            valueFrom:
              configMapKeyRef:
                name: project-env
                key: TASKS_FOLDER
        image: gharrowbm/kub-tasks-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
