apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        env:
          - name: AUTH_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: project-env
                key: AUTH_ADDRESS
        image: gharrowbm/kub-users-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
